# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

### Change the default prompt format
#format = """\
#[╭╴](238)$env_var\
#$username\
#$hostname\
#$kubernetes\
#$gcloud\
#$aws\
#$azure\
#$directory\
#$git_branch\
#$git_status
#[╰─]\
#(238)$character"""

# Use custom format
# Move the directory to the second line
format = '''
[┌───────────────────>](bold green)
[│](bold green)$all$directory$character
[└─>](bold green)
'''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'
# ~/.config/starship.toml

[aws]
format = 'on [$symbol$region]($style) '
style = 'bold blue'
symbol = '🅰 '
[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'

[directory]
truncation_length = 8
truncation_symbol = '…/'
home_symbol = '~'
# ~/.config/starship.toml

[docker_context]
format = 'via [🐋 $context](blue bold)'

[gcloud]
format = 'on [$symbol$project]($style) '
style = 'bold yellow'

[git_branch]
symbol = ''
#truncation_length = 20
#truncation_symbol = ''
ignore_branches = ['master', 'main']

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = '🏳'
ahead = '↑'
behind = '↓'
diverged = '😵'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'

[golang]
format = 'via [🏎💨 $version](bold cyan) '

[helm]
format = 'via [⎈ $version](bold white) '

[kubernetes]
format = 'on [⚙️ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_.*_(?P<var_cluster>[\\w-]+)' = 'gke-$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[lua]
format = 'via [🌕 $version](bold blue) '

[python]
symbol = ' '
pyenv_version_name = true

[shell]
fish_indicator = ''
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[sudo]
style = 'bold green'
symbol = '👩‍💻 '
disabled = false

[terraform]
format = '[🪁 $workspace]($style) '

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

